environment:
  matrix:
    #    - PYTHON: "C:\\Python27"
    #    - PYTHON: "C:\\Python27-x64"
    #    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python37-x64"

skip_commits:
  files:
    # - "*.yml"
    - "*.rst"
    - "LICENSE"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build_script:
  - "%PYTHON%\\python.exe manage.py runserver"
  - exit
